apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-08-14T02:17:52Z"
  labels:
    app: hello-minikube
  name: hello-minikube
  namespace: default
  resourceVersion: "1163282"
  uid: 27f69d51-7ebc-43b4-9464-8223efd82272
spec:
  clusterIP: 10.103.73.170
  clusterIPs:
  - 10.103.73.170
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31244
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-minikube
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
